// DO NOT EDIT — generated from ../api/openapi.json — run npm run generate:api-types to regenerate
/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description Returns ok if process is alive
         */
        get: operations["HealthController_liveness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness probe
         * @description Checks Postgres and Redis connectivity
         */
        get: operations["HealthController_readiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get API status
         * @description Returns service status and version
         */
        get: operations["StatusController_getStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthLiveResponseDto: {
            /**
             * @description Liveness status
             * @example ok
             */
            status: string;
            /**
             * Format: date-time
             * @example 2024-01-01T00:00:00.000Z
             */
            timestamp: string;
        };
        HealthChecksDto: {
            /**
             * @description Postgres status
             * @example up
             * @enum {string}
             */
            postgres: "up" | "down";
            /**
             * @description Redis status
             * @example up
             * @enum {string}
             */
            redis: "up" | "down";
        };
        HealthReadyResponseDto: {
            /**
             * @description Overall readiness
             * @example ok
             * @enum {string}
             */
            status: "ok" | "error";
            /** @description Dependency checks */
            checks: components["schemas"]["HealthChecksDto"];
            /**
             * @description Details when not ready
             * @example postgres unavailable
             */
            details?: string;
        };
        StatusResponseDto: {
            /**
             * @description Service status
             * @example ok
             */
            status: string;
            /**
             * @description API version
             * @example v1
             */
            version: string;
            /**
             * @description Service name
             * @example buildflow-api
             */
            service: string;
            /**
             * Format: date-time
             * @description Current timestamp ISO 8601 UTC
             * @example 2024-01-01T00:00:00.000Z
             */
            timestamp: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    HealthController_liveness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Liveness status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthLiveResponseDto"];
                };
            };
        };
    };
    HealthController_readiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ready */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthReadyResponseDto"];
                };
            };
            /** @description Not ready */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthReadyResponseDto"];
                };
            };
        };
    };
    StatusController_getStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description API status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponseDto"];
                };
            };
        };
    };
}
