/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/health/live": {
    get: operations["HealthController_liveness"];
  };
  "/health/ready": {
    get: operations["HealthController_readiness"];
  };
  "/api/v1/status": {
    get: operations["StatusController_getStatus"];
  };
  "/api/v1/auth/login": {
    /** Worker login with email and password */
    post: operations["AuthController_login"];
  };
  "/api/v1/me": {
    /** Get current authenticated user */
    get: operations["MeController_me"];
  };
  "/api/v1/auth/logout": {
    /** Logout current session */
    post: operations["AuthController_logout"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    LoginDto: {
      /**
       * @description Worker email
       * @example worker1@example.com
       */
      email: string;
      /**
       * @description Account password
       * @example Password123!
       */
      password: string;
    };
    LoginResponseUserDto: {
      /** @example clx123 */
      id: string;
      /** @example worker1@example.com */
      email: string;
      /**
       * @example WORKER
       * @enum {string}
       */
      role: "WORKER" | "ADMIN" | "COORDINATOR";
      /**
       * @example ACTIVE
       * @enum {string}
       */
      status: "ACTIVE" | "LOCKED" | "DISABLED";
    };
    LoginResponseDto: {
      /** @example a1b2c3... */
      token: string;
      user: components["schemas"]["LoginResponseUserDto"];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  HealthController_liveness: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  HealthController_readiness: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  StatusController_getStatus: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  /** Worker login with email and password */
  AuthController_login: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginDto"];
      };
    };
    responses: {
      /** @description Login success, returns opaque bearer token */
      200: {
        content: {
          "application/json": components["schemas"]["LoginResponseDto"];
        };
      };
      /** @description Validation error - problem-details */
      400: {
        content: never;
      };
      /** @description Invalid credentials (generic, no existence leak) */
      401: {
        content: never;
      };
    };
  };
  /** Get current authenticated user */
  MeController_me: {
    responses: {
      /** @description Current user */
      200: {
        content: never;
      };
      /** @description Unauthorized - invalid or missing token */
      401: {
        content: never;
      };
    };
  };
  /** Logout current session */
  AuthController_logout: {
    responses: {
      /** @description Logged out, session revoked */
      204: {
        content: never;
      };
      /** @description Unauthorized - invalid or missing token */
      401: {
        content: never;
      };
    };
  };
}
